services:
  user-profile-matcher:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
      - API_HOST=user-profile-matcher
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
    ports:
      - "5005:80"

  postgres:
    image: postgres:17.2-alpine
    build:
      context: .
      dockerfile: DockerfileDB
    restart: unless-stopped
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
        - POSTGRES_INITDB_ARGS=--auth=scram-sha-256
    ports:
        - 5432:5432
    volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./scripts:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
    postgres_data:
