#version: "3"
services:

  user-profile-matcher:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
      - API_HOST=user-profile-matcher
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "5005:80"

  postgres:
    image: postgres:17.2-alpine
    restart: unless-stopped
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
    ports:
        - 5432:5432
    volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
